### ISSUE TITLE
rpi_tempmon.py -c 60 -l vs rpi_tempmon.py -l -c 60

### ISSUE THREAD

**Issue by seanspotatobusiness** [gavinlyonsrepo/raspberrypi_tempmon#1]
Hi. Is `rpi_tempmon.py -c 60 -l` supposed to give the same result as `rpi_tempmon.py -l -c 60` ? I thought they would behave the same but they don't. `rpi_tempmon.py -c 60 -l` works as expected but `rpi_tempmon.py -l -c 60` checks the temperature many times per second.

**Comment by gavinlyonsrepo** [comment]
Hi 

As it says in the  readme   _"Options (standalone cannot be combined):"_
The program was never designed to mix options.
Some combinations might work together by chance due to flow of code.

I will edit the readme to make it more clearer. 

Regards
