### ISSUE TITLE
Log file not found ..???s

### ISSUE THREAD

**Issue by JunHyeokC** [gavinlyonsrepo/raspberrypi_tempmon#4]
**Hi, my name is Junhyeokc Choi in korea , i'm beginner kkk!**

now days, we want a measurement temperature of raspberry'CPU
so that, i used to ur github,
however, we have little problem
when i wording to "rpi_tempmon.py -g" "2"
opened graph, but not measured temp and usages. 
Plz help me

thank a lot.

**Comment by gavinlyonsrepo** [comment]
Hi 

You run rpi_tempmon.py -g to enter graph mode, where the menu is presented. 

Menu Option 1 to 8 require historical logfile data to be present created by logfile mode "rpi_tempmon.py -l" See readme for more details

Menu Option 9-12 use live data these should work without logfile data present.

![graphmenu](https://user-images.githubusercontent.com/21970139/218758864-39049cde-e167-419b-8d78-a480e8823b78.png)

Regards
